In [2]:
#Import libraries
# ── CORE LIBRARIES ────────────────────────────────────
import os
import time
import pickle
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
#Importing the datasets
import pandas as pd
tira = pd.read_csv(
    "C:/Users/preethi/Downloads/tira_campaign_data_with_nulls.csv",encoding="latin1")

purplle = pd.read_csv(
    "C:/Users/preethi/Downloads/purplle_campaign_data_with_nulls.csv",encoding="latin1")

nykaa = pd.read_csv(
    "C:/Users/preethi/Downloads/nykaa_campaign_data_with_nulls.csv",encoding="latin1")

In [5]:
#Understand nykaa dataset
nykaa.head(2)
nykaa.info()
nykaa.shape
nykaa.isnull().sum()
nykaa.describe().T

<class 'pandas.DataFrame'>
RangeIndex: 55555 entries, 0 to 55554
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Campaign_ID       55555 non-null  str
 1   Campaign_Type     52696 non-null  str
 2   Target_Audience   52794 non-null  str
 3   Duration          52665 non-null  float64
 4   Channel_Used      52750 non-null  str
 5   Impressions       52775 non-null  float64
 6   Clicks            52773 non-null  float64
 7   Leads             52776 non-null  float64
 8   Conversions       52889 non-null  float64
 9   Revenue           52743 non-null  float64
 10  Acquisition_Cost  52742 non-null  float64
 11  ROI               52730 non-null  float64
 12  Language          52787 non-null  str
 13  Engagement_Score  52806 non-null  float64
 14  Customer_Segment  52767 non-null  str
 15  Date              52797 non-null  str
dtypes: float64(9), str(7)
memory usage: 10.9 MB

,count,mean,std,min,25%,50%,75%,max
Duration,52665.0,17.444508,7.515052,5.00,11.00,17.00,24.00,30.00
Impressions,52775.0,55119.386698,25913.116620,10001.00,32748.00,55189.00,77535.50,100000.00
Clicks,52773.0,4690.636879,3178.575040,202.00,2113.00,3909.00,6697.00,14868.00
Leads,52776.0,1876.938684,1435.723927,56.00,778.00,1479.00,2606.00,8876.00
Conversions,52889.0,1033.357239,863.080820,20.00,400.00,778.00,1415.00,6686.00
Revenue,52743.0,515670.428626,490023.373343,6183.00,177379.00,359832.00,688120.00,4579910.00
Acquisition_Cost,52742.0,377.587214,542.150864,9.43,105.15,207.23,428.50,15473.16
ROI,52730.0,2.718973,4.492699,-0.97,0.04,1.25,3.63,74.42
Engagement_Score,52806.0,13.781463,6.351002,2.60,8.36,13.61,18.85,30.91

In [7]:
#Understand purplle data
purplle.head(2)
purplle.shape
purplle.info()
purplle.isnull().sum()
purplle.describe().T

<class 'pandas.DataFrame'>
RangeIndex: 55555 entries, 0 to 55554
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Campaign_ID       52871 non-null  str
 1   Campaign_Type     52765 non-null  str
 2   Target_Audience   52808 non-null  str
 3   Duration          52787 non-null  float64
 4   Channel_Used      52811 non-null  str
 5   Impressions       52834 non-null  float64
 6   Clicks            52843 non-null  float64
 7   Leads             52901 non-null  float64
 8   Conversions       52881 non-null  float64
 9   Revenue           52792 non-null  float64
 10  Acquisition_Cost  52857 non-null  float64
 11  ROI               52824 non-null  float64
 12  Language          52810 non-null  str
 13  Engagement_Score  52953 non-null  float64
 14  Customer_Segment  52879 non-null  str
 15  Date              52904 non-null  str
dtypes: float64(9), str(7)
memory usage: 10.9 MB

,count,mean,std,min,25%,50%,75%,max
Duration,52787.0,17.487279,7.492281,5.00,11.00,17.00,24.00,30.00
Impressions,52834.0,55081.247398,25955.720822,10001.00,32658.50,55134.00,77700.00,100000.00
Clicks,52843.0,4682.958973,3179.537407,207.00,2111.00,3901.00,6705.50,14888.00
Leads,52901.0,1873.141907,1432.215726,48.00,781.00,1474.00,2597.00,8613.00
Conversions,52881.0,1027.354324,857.583756,19.00,399.00,772.00,1402.00,6221.00
Revenue,52792.0,513567.979789,487649.377889,6061.00,177075.00,357884.00,686766.00,4345920.00
Acquisition_Cost,52857.0,377.986979,536.908374,9.34,107.38,210.12,431.88,12109.05
ROI,52824.0,2.681688,4.474675,-0.97,0.04,1.22,3.55,66.84
Engagement_Score,52953.0,13.756857,6.334863,2.56,8.34,13.57,18.79,30.99

In [8]:
#Understand tira dataset
tira.head(2)
tira.shape
tira.info()
tira.isnull().sum()
tira.describe().T

<class 'pandas.DataFrame'>
RangeIndex: 55555 entries, 0 to 55554
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Campaign_ID       52822 non-null  str
 1   Campaign_Type     52846 non-null  str
 2   Target_Audience   52891 non-null  str
 3   Duration          52890 non-null  float64
 4   Channel_Used      52822 non-null  str
 5   Impressions       52832 non-null  float64
 6   Clicks            52825 non-null  float64
 7   Leads             52898 non-null  float64
 8   Conversions       52895 non-null  float64
 9   Revenue           52826 non-null  float64
 10  Acquisition_Cost  52905 non-null  float64
 11  ROI               52813 non-null  float64
 12  Language          52769 non-null  str
 13  Engagement_Score  52825 non-null  float64
 14  Customer_Segment  52844 non-null  str
 15  Date              52865 non-null  str
dtypes: float64(9), str(7)
memory usage: 10.9 MB

,count,mean,std,min,25%,50%,75%,max
Duration,52890.0,17.533768,7.497857,5.00,11.00,18.00,24.00,30.00
Impressions,52832.0,55005.698421,26016.433598,10001.00,32426.00,54980.00,77513.25,99999.00
Clicks,52825.0,4681.332343,3174.005400,208.00,2108.00,3912.00,6681.00,14944.00
Leads,52898.0,1866.431831,1422.867526,50.00,778.00,1475.00,2596.75,8761.00
Conversions,52895.0,1024.783325,852.359561,17.00,402.00,775.00,1391.00,6415.00
Revenue,52826.0,512244.447715,485101.816397,3895.00,178065.00,359054.00,682263.00,4517478.00
Acquisition_Cost,52905.0,374.920868,531.010003,8.18,107.48,208.71,425.88,15038.00
ROI,52813.0,2.687977,4.488936,-0.99,0.06,1.24,3.56,79.30
Engagement_Score,52825.0,13.756235,6.298586,2.58,8.43,13.57,18.72,30.52

In [5]:
#Adding new columns in all dataset
nykaa.insert(1, 'Brand', 'Nykaa')
purplle.insert(1, 'Brand', 'Purplle')
tira.insert(1, 'Brand', 'Tira')

In [6]:
#Combining all the 3 dataset
combined_data = pd.concat([nykaa, purplle, tira], ignore_index=True)
combined_data.head(2)
combined_data.shape

(166665, 17)

In [7]:
#Formatting the date column
combined_data['Date'] = pd.to_datetime(combined_data['Date'], format='%d-%m-%Y')
combined_data

,Campaign_ID,Brand,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
0,NY-CMP-1000,Nykaa,Social Media,College Students,21.0,"WhatsApp, YouTube",57804.0,6156.0,3616.0,2355.0,1867515.0,NaN,6.14,Hindi,20.98,College Students,2025-04-29
1,NY-CMP-1001,Nykaa,Paid Ads,Tier 2 City Customers,18.0,YouTube,91801.0,3321.0,1971.0,1357.0,1046247.0,180.83,3.26,Hindi,7.24,College Students,2025-04-06
2,NY-CMP-1002,Nykaa,Influencer,Youth,23.0,"WhatsApp, Google, YouTube",15536.0,2182.0,952.0,755.0,197055.0,90.60,NaN,English,25.03,College Students,2025-01-14
3,NY-CMP-1003,Nykaa,Email,Working Women,18.0,"YouTube, Facebook, Instagram",88114.0,8413.0,2231.0,947.0,376906.0,249.07,0.60,Hindi,13.15,NaN,2025-06-04
4,NY-CMP-1004,Nykaa,Paid Ads,College Students,10.0,"Facebook, Instagram",96871.0,3743.0,2060.0,1258.0,518296.0,228.60,0.80,Hindi,7.29,Tier 2 City Customers,2024-12-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166660,NaN,Tira,NaN,Tier 2 City Customers,11.0,"Instagram, YouTube, Email",NaN,3799.0,NaN,1099.0,454986.0,213.21,0.94,Bengali,10.70,Youth,2024-11-12
166661,TI-CMP-56551,Tira,SEO,Working Women,20.0,"Google, Instagram",54886.0,1578.0,634.0,NaN,136514.0,436.24,-0.09,English,4.66,Working Women,2024-08-25
166662,TI-CMP-56552,Tira,Email,NaN,13.0,"Facebook, Instagram",97954.0,11480.0,4567.0,2144.0,445952.0,78.77,1.64,NaN,18.57,Premium Shoppers,2025-04-15
166663,NaN,Tira,Influencer,Premium Shoppers,22.0,"Google, Email",11669.0,NaN,122.0,44.0,26884.0,NaN,-0.76,English,5.35,Working Women,2024-07-21
166664,TI-CMP-56554,Tira,Paid Ads,Working Women,NaN,Instagram,50497.0,1604.0,542.0,363.0,281688.0,151.44,4.12,English,4.97,Premium Shoppers,2025-05-02

In [8]:
# Fill missing Revenue with 0
combined_data['Revenue'] = combined_data['Revenue'].fillna(0)
combined_data[combined_data['Revenue'].isnull()]

Empty DataFrame
Columns: [Campaign_ID, Brand, Campaign_Type, Target_Audience, Duration, Channel_Used, Impressions, Clicks, Leads, Conversions, Revenue, Acquisition_Cost, ROI, Language, Engagement_Score, Customer_Segment, Date]
Index: []

In [9]:
#Fill missing Acquisition_Cost with the mean
mean_val = combined_data['Acquisition_Cost'].mean()
combined_data['Acquisition_Cost'] = combined_data['Acquisition_Cost'].fillna(mean_val)
combined_data[combined_data['Acquisition_Cost'].isnull()]
print(f"✅ Acquisition_Cost → filled with mean: {mean_val:.2f}")

✅ Acquisition_Cost → filled with mean: 376.83

In [10]:
#changing null value from language  to native 

combined_data['Language'] = combined_data['Language'].fillna('Native')
combined_data['Customer_Segment'] = combined_data['Customer_Segment'].fillna('Basic Plan')

In [11]:
# changing null value from 'Campaign_Type', 'Target_Audience','Channel_Used', as Mode 

categorical_cols = ['Campaign_Type', 'Target_Audience', 'Channel_Used']
for col in categorical_cols:
    mode_val = combined_data[col].mode()[0]
    combined_data[col] = combined_data[col].fillna(mode_val)
    
    print(f"✅ {col} → filled with mode: {mode_val}")

✅ Campaign_Type → filled with mode: Influencer
✅ Target_Audience → filled with mode: Premium Shoppers
✅ Channel_Used → filled with mode: Email

In [12]:
# numeric colume  as median 
numerical_cols = ['Duration', 'Impressions', 'Clicks', 'Leads', 'Conversions', 'Engagement_Score']

for col in numerical_cols:
    median_val = combined_data[col].median()
    combined_data[col] = combined_data[col].fillna(median_val)
    print(f"✅ {col} → filled with median: {median_val:.2f}")

✅ Duration → filled with median: 17.00
✅ Impressions → filled with median: 55113.00
✅ Clicks → filled with median: 3908.00
✅ Leads → filled with median: 1476.00
✅ Conversions → filled with median: 775.00
✅ Engagement_Score → filled with median: 13.59

In [13]:
#Checking null values in dataset
combined_data.isnull().sum()

Campaign_ID         5417
Brand                  0
Campaign_Type          0
Target_Audience        0
Duration               0
Channel_Used           0
Impressions            0
Clicks                 0
Leads                  0
Conversions            0
Revenue                0
Acquisition_Cost       0
ROI                 8298
Language               0
Engagement_Score       0
Customer_Segment       0
Date                8099
dtype: int64

In [14]:
#Checking Duplicates in dataset
combined_data.duplicated().sum()

np.int64(0)

In [15]:
# create new column as Updated_ROI as current ROI is wrong 

combined_data['Updated_ROI'] = (
    (combined_data['Revenue'] - combined_data['Acquisition_Cost'])
    / combined_data['Acquisition_Cost']).round(2)

In [16]:
# moving the colum near to old ROI 
roi_pos = combined_data.columns.get_loc('ROI')
col = combined_data.pop('Updated_ROI')
combined_data.insert(roi_pos + 1, 'Updated_ROI', col)
combined_data.isnull().sum()

Campaign_ID         5417
Brand                  0
Campaign_Type          0
Target_Audience        0
Duration               0
Channel_Used           0
Impressions            0
Clicks                 0
Leads                  0
Conversions            0
Revenue                0
Acquisition_Cost       0
ROI                 8298
Updated_ROI            0
Language               0
Engagement_Score       0
Customer_Segment       0
Date                8099
dtype: int64

In [17]:
# replace 0.00 in old ROI data to avoid nul values 
combined_data['ROI'] = combined_data['ROI'].fillna('0.00')

In [18]:
# Spliting the Channel_Used into multiple column (Multi-level (multi-label) encoding for Channel_Used)
# Cell 1 — Find unique channels
all_channels = (
    combined_data['Channel_Used'].str.split(',').explode().str.strip().unique())

sorted(all_channels)
print("Total unique channels:", len(all_channels))

Total unique channels: 6

In [19]:
channel_dummies = combined_data['Channel_Used'].str.get_dummies(sep=', ')
channel_dummies
channel_dummies.columns.tolist()

['Email', 'Facebook', 'Google', 'Instagram', 'WhatsApp', 'YouTube']

In [20]:
channel_pos = combined_data.columns.get_loc('Channel_Used')
for i, col in enumerate(channel_dummies.columns):
    combined_data.insert(channel_pos + 1 + i, col, channel_dummies[col])
combined_data.head(2)

,Campaign_ID,Brand,Campaign_Type,Target_Audience,Duration,Channel_Used,Email,Facebook,Google,Instagram,...,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Updated_ROI,Language,Engagement_Score,Customer_Segment,Date
0,NY-CMP-1000,Nykaa,Social Media,College Students,21.0,"WhatsApp, YouTube",0,0,0,0,...,3616.0,2355.0,1867515.0,376.83056,6.14,4954.85,Hindi,20.98,College Students,2025-04-29
1,NY-CMP-1001,Nykaa,Paid Ads,Tier 2 City Customers,18.0,YouTube,0,0,0,0,...,1971.0,1357.0,1046247.0,180.83000,3.26,5784.80,Hindi,7.24,College Students,2025-04-06

In [21]:
#Dropping columns
combined_data.drop(columns=['Campaign_ID'], inplace=True)
combined_data.drop(columns=['ROI'], inplace=True)

In [22]:
#Checking null values
combined_data.isnull().sum()

Brand                  0
Campaign_Type          0
Target_Audience        0
Duration               0
Channel_Used           0
Email                  0
Facebook               0
Google                 0
Instagram              0
WhatsApp               0
YouTube                0
Impressions            0
Clicks                 0
Leads                  0
Conversions            0
Revenue                0
Acquisition_Cost       0
Updated_ROI            0
Language               0
Engagement_Score       0
Customer_Segment       0
Date                8099
dtype: int64

In [23]:
# updating random date in dates
null_count = combined_data['Date'].isnull().sum()
existing_dates = combined_data['Date'].dropna()

In [24]:
import numpy as np
np.random.seed(42)
random_dates = existing_dates.sample(n=null_count, replace=True).values
print(f"Generated {len(random_dates)} random dates")
print(f"Sample of generated dates: {random_dates[:5]}")

Generated 8099 random dates
Sample of generated dates: ['2024-07-09T00:00:00.000000' '2024-12-03T00:00:00.000000'
 '2024-08-26T00:00:00.000000' '2024-07-28T00:00:00.000000'
 '2024-07-24T00:00:00.000000']

In [25]:
combined_data.loc[combined_data['Date'].isnull(), 'Date'] = random_dates
combined_data['Date'].isnull().sum()
combined_data['Date'].min(), "→", combined_data['Date'].max()

(Timestamp('2024-07-01 00:00:00'), '→', Timestamp('2025-06-24 00:00:00'))

In [26]:
combined_data['Date'] = pd.to_datetime(combined_data['Date'])
# Convert Date to datetime first
combined_data['Date'] = pd.to_datetime(combined_data['Date'])

# Create only Month_Name in Apr'25 format
combined_data['Month_Name'] = combined_data['Date'].dt.strftime("%b'%y")

# Verify
print(combined_data[['Date', 'Month_Name']].head(10))

        Date Month_Name
0 2025-04-29     Apr'25
1 2025-04-06     Apr'25
2 2025-01-14     Jan'25
3 2025-06-04     Jun'25
4 2024-12-29     Dec'24
5 2024-09-23     Sep'24
6 2024-09-01     Sep'24
7 2025-05-31     May'25
8 2025-03-24     Mar'25
9 2025-04-29     Apr'25

In [27]:
#Drop Date and Channel_Used columns

combined_data.drop(columns=['Channel_Used'], inplace=True)
combined_data.drop(columns=['Date'], inplace=True)

In [28]:
combined_data

,Brand,Campaign_Type,Target_Audience,Duration,Email,Facebook,Google,Instagram,WhatsApp,YouTube,...,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,Updated_ROI,Language,Engagement_Score,Customer_Segment,Month_Name
0,Nykaa,Social Media,College Students,21.0,0,0,0,0,1,1,...,6156.0,3616.0,2355.0,1867515.0,376.83056,4954.85,Hindi,20.98,College Students,Apr'25
1,Nykaa,Paid Ads,Tier 2 City Customers,18.0,0,0,0,0,0,1,...,3321.0,1971.0,1357.0,1046247.0,180.83000,5784.80,Hindi,7.24,College Students,Apr'25
2,Nykaa,Influencer,Youth,23.0,0,0,1,0,1,1,...,2182.0,952.0,755.0,197055.0,90.60000,2174.00,English,25.03,College Students,Jan'25
3,Nykaa,Email,Working Women,18.0,0,1,0,1,0,1,...,8413.0,2231.0,947.0,376906.0,249.07000,1512.25,Hindi,13.15,Basic Plan,Jun'25
4,Nykaa,Paid Ads,College Students,10.0,0,1,0,1,0,0,...,3743.0,2060.0,1258.0,518296.0,228.60000,2266.26,Hindi,7.29,Tier 2 City Customers,Dec'24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166660,Tira,Influencer,Tier 2 City Customers,11.0,1,0,0,1,0,1,...,3799.0,1476.0,1099.0,454986.0,213.21000,2132.98,Bengali,10.70,Youth,Nov'24
166661,Tira,SEO,Working Women,20.0,0,0,1,1,0,0,...,1578.0,634.0,775.0,136514.0,436.24000,311.93,English,4.66,Working Women,Aug'24
166662,Tira,Email,Premium Shoppers,13.0,0,1,0,1,0,0,...,11480.0,4567.0,2144.0,445952.0,78.77000,5660.44,Native,18.57,Premium Shoppers,Apr'25
166663,Tira,Influencer,Premium Shoppers,22.0,1,0,1,0,0,0,...,3908.0,122.0,44.0,26884.0,376.83056,70.34,English,5.35,Working Women,Jul'24
166664,Tira,Paid Ads,Working Women,17.0,0,0,0,1,0,0,...,1604.0,542.0,363.0,281688.0,151.44000,1859.06,English,4.97,Premium Shoppers,May'25

In [29]:
# Save cleaned combined_data to a new CSV file
combined_data.to_csv(r'../data/cleaned_campaign_data.csv', index=False)

print("✅ File saved successfully!")
print("Shape:", combined_data.shape)
print("Columns:", combined_data.columns.tolist())

✅ File saved successfully!
Shape: (166665, 21)
Columns: ['Brand', 'Campaign_Type', 'Target_Audience', 'Duration', 'Email', 'Facebook', 'Google', 'Instagram', 'WhatsApp', 'YouTube', 'Impressions', 'Clicks', 'Leads', 'Conversions', 'Revenue', 'Acquisition_Cost', 'Updated_ROI', 'Language', 'Engagement_Score', 'Customer_Segment', 'Month_Name']